### ISSUE TITLE
Mosque Details Need to be called from DB in Mosque Details page

### ISSUE THREAD

**Issue by mohamadrais** [mohamadrais/tm-saff#2]
1. Mosque name
2. Address
<img width="366" alt="screen shot 2018-08-15 at 11 15 34 am" src="https://user-images.githubusercontent.com/28695979/46249144-15b23700-c457-11e8-89a4-695cb2773ca4.png">

**Comment by newhill** [comment]
aishah: fix applied (home page fetches mosque info from DB, if not in registered->take from google api). when open mosque detail, home page should send params of mosque info to mosque detail page
