### ISSUE TITLE
Create Moderator/Ustaz

### ISSUE THREAD

**Issue by mohamadrais** [mohamadrais/tm-saff#8]
Create ustaz profile from mosque's admin.
<img width="330" alt="screen shot 2018-09-30 at 2 32 31 am" src="https://user-images.githubusercontent.com/28695979/46249288-37142280-c459-11e8-9a6d-250ef5512e68.png">

**Comment by newhill** [comment]
completed. please re-test.

**Comment by mohamadrais** [comment]
tested and well done
